#!/usr/bin/env ruby
RAILS_CONNECTION_ADAPTERS = %w[sqlite]

#
# Serves all examples, mounted into Webrick.
#
$:.unshift File.expand_path(File.dirname(__FILE__) + "/../lib")
require 'stringio'
require 'webrick/httpserver'
require 'camping'

# All applications share a single database
Camping::Models::Base.establish_connection :adapter => 'sqlite3', :database => 'serve.db'
Camping::Models::Base.logger = Logger.new('camping.log')

# Find the working applications
apps = 
    Dir['*'].select do |d|
        if File.directory? "#{d}"
            begin
                load "#{d}/#{d}.rb"
                true
            rescue Exception => e
                puts "Camping app `#{d}' will not load: #{e.class} #{e.message}"
            end
        end
    end
apps.map! do |app|
    begin
        klass = Object.const_get(Object.constants.grep(/^#{app}$/i)[0])
        klass.create if klass.respond_to? :create
        [app, klass]
    rescue Exception => e
        puts "Camping app `#{app}' will not load: #{e.class} #{e.message}"
    end
end
apps.compact!

s = WEBrick::HTTPServer.new(:BindAddress => '0.0.0.0', :Port => 3301)

# Root mount displays applications mounted
s.mount_proc("/") do |req, resp|
    welcome = "Welcome to the Camping Example Server"
    b = Markaby::Builder.new({}, {})
    b = b.instance_eval do
        html do
            head do
                title welcome
                style <<-END, :type => 'text/css'
                    body { 
                        font-family: verdana, arial, sans-serif; 
                        padding: 10px 40px; 
                        margin: 0; 
                    }
                    h1, h2, h3, h4, h5, h6 {
                        font-family: utopia, georgia, serif;
                    }
                END
            end
            body do
                h1 welcome
                p %{
                    Good day.  These are the Camping sample applications.  The code
                    for each of these applications is available in its own folder
                    under examples.  A link to the application's source code is 
                    also given next to each one.
                }
                p %{Well, click on the application's name to give a try.}
                ul do
                    apps.each do |app, klass|
                        li do
                            h3(:style => "display: inline") { a app, :href => "/#{app}" }
                            small { text " / " ; a "View Source", :href => "/code/#{app}" }
                        end
                    end
                end
            end
        end
    end
    resp.body = b.to_s
end

# Mount which handles each application
apps.each do |app, klass|
    # Mount for view source
    s.mount_proc("/code/#{app}") do |req, resp|
        resp.header['Content-Type'] = 'text/plain'
        resp.body = File.read("#{app}/#{app}.rb")
    end

    s.mount_proc("/#{app}") do |req, resp|
        controller = klass.run((req.body and StringIO.new(req.body)), req.meta_vars)
        resp.status = controller.status
        controller.headers.each do |k, v|
            [*v].each do |vi|
                resp[k] = vi
            end
        end
        resp.body = controller.body
        nil
    end
end

# Server up
trap(:INT) do
    s.shutdown
end
s.start
