#!/usr/bin/env ruby
#
# Serves all examples, mounted into Webrick.
#
require 'stringio'
require 'webrick/httpserver'

dir = Dir.pwd
apps = 
    Dir['*'].select do |d|
        Dir.chdir(dir)
        if File.exists? "#{d}/#{d}.rb"
            begin
                Dir.chdir("#{dir}/#{d}")
                load "#{d}.rb"
                true
            rescue Exception => e
                puts "Camping app `#{d}' will not load: #{e.class} #{e.message}"
            end
        end
    end
apps.map! do |app|
    [app, (Object.const_get(Object.constants.grep(/^#{app}$/i)[0]) rescue nil)]
end

s = WEBrick::HTTPServer.new(:BindAddress => '0.0.0.0', :Port => 3301)
apps.each do |app, klass|
    s.mount_proc("/#{app}") do |req, resp|
        Object.instance_eval do
            remove_const :ENV
            const_set :ENV, req.meta_vars
        end
        def resp.<<(data)
            raw_header, body = "#{data}".split(/^[\xd\xa]+/on, 2) 

            begin
              header = WEBrick::HTTPUtils::parse_header(raw_header)
              if /^(\d+)/ =~ header['status'][0]
                self.status = $1.to_i
                header.delete('status')
              end
              header.each{|key, val| self[key] = val.join(", ") }
            rescue => ex
              raise WEBrick::HTTPStatus::InternalServerError, ex.message
            end
            self.body = body
        end
        Dir.chdir("#{dir}/#{app}")
        klass.run((req.body and StringIO.new(req.body)), resp)
        Dir.chdir(dir)
        nil
    end
end
trap(:INT) do
    s.shutdown
end
s.start
